#!/usr/bin/env node

'use strict';

var gith = require('gith').create(9001);
var spawn = require('child_process').spawn;
var build = require('nico').build;

build({});

gith({
  repo: 'popomore/chuome',
  branch: 'master'
}).on('all', function() {
  console.log('=======      git pull       =======');
  var pull = spawn('git', ['pull', 'origin', 'master'], {cwd: __dirname, stdio: 'inherit'});
  pull.on('close', function(code) {
    if (code === 0) {
      console.log('=======  git pull success   =======');
      build({});
      console.log('======= nico build complete =======');
      console.log('======= ' + new Date().toString() + ' =======');
    } else {
      console.log('=======   git pull failed   =======');
      console.log('======= ' + new Date().toString() + ' =======');
    }
  });
});
